#!/bin/sh
set -e

# project variables
export PROJECT_NAME=example-java
export BUILD_TYPE="java docker"
export PUSH_TYPE=
export DEPLOY_TYPE=

# execute variables
IMAGE=nodevops/example-java-agent && [ "$1" = "build" ] && IMAGE=nodevops/example-java-builder
VOLUMES=${VOLUMES:-"-v $PWD:/workspace -v /var/run/docker.sock:/var/run/docker.sock"}
test -t 1 && USE_TTY="-t" 
if [ "$1" = "build" ] && [ ! -z $USE_CACHES ]; then
	 [ -e $HOME/.m2 ] && VOLUMES="$VOLUMES -v $HOME/.m2:/root/.m2"
fi
[ ! -z "$DOCKER_CERT_PATH" ] && VOLUMES="$VOLUMES -v $DOCKER_CERT_PATH:$DOCKER_CERT_PATH"
CID=$(head -1 /proc/self/cgroup 2> /dev/null | cut -d/ -f3)
[ ! -z $CID ] && VOLUMES="--volumes-from=$CID"

# run docker agent
docker run -i $USE_TTY --rm \
	$VOLUMES \
	 -e BUILD_TYPE -e PUSH_TYPE -e DEPLOY_TYPE -e OPS_TYPE -e DOCKER_REGISTRY -e DOCKER_TLS_VERIFY -e DOCKER_HOST -e DOCKER_CERT_PATH -e DOCKER_API_VERSION -e USE_CACHES -e NO_PROMPT -e NO_DETECT -e GITHUB_USER -e GITHUB_TOKEN -e GITHUB_URL -e GITHUB_API -e WEBHOOK_SECRET \
	$IMAGE "$@"
