#!/bin/sh
set -e
export PROJECT_NAME=getting-started
export BUILD_TYPE="go
docker"
export PUSH_TYPE=docker
export DEPLOY_TYPE=docker
export OPS_TYPE=github
export GITHUB_URL=github.com
export GITHUB_API=https://api.github.com
export GITHUB_USER=noodevops
export DOCKER_REGISTRY=localhost:5000

IMAGE=nodevops/getting-started-agent
VOLUMES=${VOLUMES:-"-v $PWD:/workspace -v /var/run/docker.sock:/var/run/docker.sock"}
[ ! -z "" ] && VOLUMES="$VOLUMES -v $DOCKER_CERT_PATH:$DOCKER_CERT_PATH"

if [ "$1" = "build" ]; then
	IMAGE=nodevops/getting-started-builder
	[ ! -z $USE_CACHES ] && [ -e $HOME/.m2 ] && VOLUMES="$VOLUMES -v $HOME/.m2:/root/.m2"
fi
test -t 1 && USE_TTY="-t" 

CID=$(head -1 /proc/self/cgroup 2> /dev/null | cut -d/ -f3)
[ ! -z $CID ] && VOLUMES="--volumes-from=$CID"

docker run -i $USE_TTY --rm 	$VOLUMES 	 -e BUILD_TYPE -e PUSH_TYPE -e DEPLOY_TYPE -e OPS_TYPE -e DOCKER_REGISTRY -e DOCKER_TLS_VERIFY -e DOCKER_HOST -e DOCKER_CERT_PATH -e DOCKER_API_VERSION -e USE_CACHES -e NO_PROMPT -e NO_DETECT -e GITHUB_USER -e GITHUB_TOKEN -e GITHUB_URL -e GITHUB_API -e WEBHOOK_SECRET 	$IMAGE "$@"
